spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/collge-app/collge-config-server
          clone-on-start: true
      fail-fast: true
  application:
    name: "CONFIG-SERVER"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


server:
  port: 8888