spring:
  application:
    name: USER-SERVICE
  datasource:
    username: ""
    password: ""
    url: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    baseline-on-migrate: true
    user: ""
    password: ""
    enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9091

service-urls:
  baseEndpoint: http://localhost:9092

#// DIGITAL OCEAN CREDENTIALS
do:
  spaces:
    accessKey: ""
    secretKey: ""
