spring:
  application:
    name: SEARCH-SERVICE
  datasource:
    username: ""
    password: ""
    url: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9093

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
