spring:
  application:
    name: NOTIFICATION-SERVICE
  data:
    mongodb:
      uri: ""

service-urls:
  baseEndpoint: ""

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

server:
  port: 9095
mongock:
  change-logs-scan-package: com.collge.POSTSERVICE.config
